language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: undeadgrishnackh-github
    token:
      secure: 1ad4f5d9ab0933ba98ad2ebf03e082701f9e2951
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
#  - provider: pages
#    skip_cleanup: true
#    github_token: "$GITHUB_TOKEN"
#    on:
#      branch: master
  provider: heroku
  api_key:
    secure: "g768chRF/Y3bMRRUszKWWVUF7JEVbPe0bYdPMCu0mlZvKUHohaPn1jGSjinXRiameRTSGCNqRM+a9reyJiDI+V1DQt0FyhHcG4sZ9wB/EAjXY7Ka+D77EuduS5N2inF300Q5jy0C8+HxNDQWTz1xRIaWIYyH7MIT/er8BokhhqccN7e+0we7bLWva9NUKmU6lq/VnqATD59u5CXPOBV57VHMSMDOOk+f3rGXtzXhCTWK+lswhYMwoHxPyCdVZNxOJF9EMPFi8kpp/W8lB77Q6NZKBLLNgmlc8uO2di4l2izpF9Ru0wvhlV1UCFzbGdVrHxLC6EXQauvTYoZxqPqS0eUB9V/ezCmq0YmINMV6unXN9kk2iHUBSVq3VafzCmfL0mhQ5szvnabmIq2TxMlhEVyWTDTPtgJX6jnY/Gx2S/yGHpSVKmYcHks2pnXz8LfdPJPBj8rKhviurLivFQd8KD0vP0fEtaOQG+LW5rLU75B5PoCxk39VMTnTRkoFyoJB1MVbP38xpea5ItX/IETgE8L7eik/2IWJWAslEL1utzm7JChpffcm3s7P8lpu4dIOJESUa4ytfwj520ZYjJpjg+VhuqsxEt/yRHwcJuzYV+HSiAb0B75YQHyS7yHQip4LKlWcJZVGZ9iy7P5CWKHSNt+eguT/d7PhgaJaPe1GefA="
after_success:
- mvn clean test jacoco:report coveralls:report
