language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: undeadgrishnackh-github
    token:
      secure: 1ad4f5d9ab0933ba98ad2ebf03e082701f9e2951
jdk:
- oraclejdk14
script:
- "./gradlew sonarqube"
cache:
  directories:
  - "$HOME/.sonar/cache"
deploy:
- provider: heroku
  app: damp-inlet-50606
  api_key:
    secure: uXoS/ott0EA9cEH6wAiBmi9KbUVpYzpONHHdsbA5fuc2QR2h+tgn4UO2YXZfFV2RDq2ljq6tbo1NjOeF3O0JnIvJVu8O53abDt9wFQpnpGMq9eDpPOpkog4RpeCmtPPvLlo8CoQnVrDaZb6rmfVyDtB5YBpZHN50Z++pMS7FlQFU8uWMQvP4btkgl4u/oCEPO7pY2HM9E8oOvysN3mbN9ni5V+hv2o9uvqxo42rxW8tNkYZEx+4/D0S91f3DDTMMcT04byXwCFK7VeW0FqNUq99QiQpKLJJVH3n0FmFYJPvg7hA25p70nhDPl7V2wc59k5ovKj7z281eE2ck9iBFVnl3jKy24skYNA/yhxnOiNW2eWgBFNTlDjt7bkgKV7lXq7BE8ho9LwB+RbSXAcVfgNhtJeNpct9QQtVxp7y+qgeoZHY9yxkuP072smaRcBMJvuJXd2i0BU162rpRGMnuteBwVnCu3F3qGxzDsijPiEpAkhnMFPodaiNVn7caRC0fTfBxmk9XpAY3tsjxVRihK10JNG6t6olxsnM0B23ssQHPsGos1xQP+BY+a2kfjxOAzQaME+ZhnP469qeZ5B3osG0TFGW6Wab+KzCbAljjFgbkjNOngXezpuRYEzSrutyIMGttSxRGarJ0+hKPQD2AavJHVIvcnduDBU/582fvMHc=
notifications:
  slack:
    secure: EzpL7JCpII7WHA5Qvej2S2nr751JB6jMyM90qzglrUWk9jndoyXg265nRqA0UvbHNaffQCWf6BBTQrvu5Qb0s8kXA7bV6bOrYZLl986Cj6JVI18w68PabnXFJk9RTPwZZfQBiRdJZTOaVIYMaHdqxL1TBJAUGVirBK447P1DZA6DydWCv1JNF45S+QIL6UyMhZj7ZdlDqQlSJJt6ILvpMmj4Zb2fwbEGdewBnCfD07UwwW05IDFIYpcLxLaE3gsZYUadQq6Y3C/31jtTQGnglmGyy60e0mPE3BJu5KZnm9AbFgiw2BNyqrFzzllTKAakUK2P5mDN8vYrQErCZXGmj8x841rUbASiv+xR/c6QTITRdOzpdFrPFD7TEoU9+b2ddVev07a8VX45AhP1tMlV+utPLEJraadsOwvv7fiIfmACPXXbjSZJ4w2dge0HMjbB+J4dJF+vqJ6GYw1v9JQJmGdiPP0nOC5+0Y+GiK0Dx1eWrWmNs3DBhs6tv7KrDaRYYHGNrkibuvgiaCiyCWUa1AoTWLsX3xsUlGddc/2IK0io36M/qc6LpkpERSShilHiYI7K6qjrTbCSnlURjfrwz8PbAzpvinY8xut4GwrtbgQXg/lI4akVmtQbhI0AndwbaPQaZNAGInb+jbmZZ9KfSyFrQzSOv2DjoR6mBMsmijM=
