language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: undeadgrishnackh-github
    token:
      secure: 1ad4f5d9ab0933ba98ad2ebf03e082701f9e2951
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master
  - provider: heroku
    app: damp-inlet-50606
    api_key:
      secure: WCMVeowMKXPzMIu7puS7GAmq4dqAHuWmPkc2zexg0y/+97UvAULgSrQRy0NHDJNMqa3dDJCwyzzxtUyGMDqNkczXPeIFIK/OH2uXfCEp1Lw3u6Nj63JpdtjOgf7J9073N6nj3PNuV4rfs6zKBq362BA0OYUYKcafb0HnQrxaBHhxenlaLoi0tAjqHmmqXWxHV2ti0b7tFmC6+hWaXzMDmm++7UdmWD17h/dNIEhvEKRZjwe0NxugwOwSg6xbVTLfxpo+tjRq35TDQWVYkYrZ7kaSIeU/90c/mwTdu/ux37s0ToK4V/lOSUxsMyDOrKJ4uyfbBFGOH1StGCjlsVUhmrH6jikI712XfGXm3B8MyD8va/oHj04VMTJYLqHk/72BLHNFl6LZx1sJbnp941R3zdoxIBaCBIs4G/pLmwui59PvEskeE/2zE/6MpYVu3UUbynF92oEpNHXT+Zc14v7KAl//1fl+tT1G+SFFPlR5RvOSqv5VkTs/eT0Xg+XRTnuhdKnf3tkPYJp2gKcKVSxZtEu+05Ph+6B3VjqdOyFBZpTeFOEzMJXmXuPnNXlD0/uC/j8Jv5DPKmdIfrJR//RwpI+DEiGY0zzZ/GN+fl0JoU5V2B/baGkQqZNXkXUXjc2PJBLMX0b8LruuPUTOOYXNmevSJ6vbF8MHGFdA2Q4xZzQ=
after_success:
- mvn clean test jacoco:report coveralls:report
