language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: undeadgrishnackh-github
    token:
      secure: 1ad4f5d9ab0933ba98ad2ebf03e082701f9e2951
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
- provider: heroku
  api_key:
    secure: "jDthnWG2eKwKlTT/m0qwP2k/nib3/FwdtMEmymDe5ANRFFEOHuN65otX/SRAqOW12jlOTzCScw8nIP4ujsbsSMoMQwBXan/g0McjV0jqJ+06d2aHy6WxGgWLOdZa78FQ6+Z6YrH9Fb4h/hcrt4cVR2WeX80NG18T1ihh9z7Bqtz2h2sU99QJXZe5ZtKBVzquJS6BcnpmyWaYmn0pEaSABwPlCPbxxwC8w7fYcTAugtgIxFmBlUZrvM4+VawpZpZ/h1rsPG0OWlWGuP9PGMhvE+LkfBDGXlfJ+/MmryRxfhO2crS7jG2FmD/I3bhmSi/7L+ixTSKJpqx51fmLuiZEieWf77o4uvUNA3vP8BFQd2sMKhTSc4yqqtlJv/hXSqhZj3hB+HDuMohpKH0bkvQ+iBV5BI0e8xqs5vU3KtJfU0sj5btVn65rEl8PAYH1WC2kcEdgGQVMYlKWYh6ouWaXM0B5CV6gO9QTQJ8wpeTPgG6jOu/VhZmfRW56EVaz3+YozkXvPsrOOeM9HMk5V6vEJ8bzqEjQ3P6AgvBcwyuybYhtzSl3LOL6o2/x325wGAAS9DZUymb2pHU3DIL9oThP9MCLmo5BkZ/RDByjKaRzI0grrlclvUtgZOIkhfTEH6w90PTUF05zoKgKUvyO6WI2LFDaVE8cCeGi+leZpqk6KA8="
  app: tictactoe
  on:
    repo: undeadgrishnackh/tictactoe
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
after_success:
- mvn clean test jacoco:report coveralls:report