language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "undeadgrishnackh-github"
    token:
      secure: "1ad4f5d9ab0933ba98ad2ebf03e082701f9e2951"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
after_success:
  - coveralls