language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: undeadgrishnackh-github
    token:
      secure: 1ad4f5d9ab0933ba98ad2ebf03e082701f9e2951
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master
  - provider: heroku
    api_key:
      secure: V9jKqztHb/MdYNTpn0HbvBu/+usKvm94FuUKx207gSoxBfj9LRjQKn77+RjUJ9L1qLssG/9517ufDZfdkOVPYb7TSHDnrsTHS7wqp6Dz27CZ73f/p4maLSAbEvbQ618fqcGSxNeXQAawgz8bYnT1Fl28GMTLDrG5RKeEm9vo9gccJgT+6Zm8Eg4KAmeLoUOzuKSkm9Fcxaau9X7Q8niQE6YnVdkPGSTKGpuVJuQ0DlZTIOgld2+oPpcQQ71ZMHCpusHmBt4xr3yWug+NrEfF2K3pVwLbu02XpLPd2W8AZfEmZS75S0drU9KKbbO4qnrc/rcwmBHAZ1MV/sKWvxDtU05QTGsAOoZJzaFSwERJ8F0M/ljSl0Lj2glMuvbBd32883IAdfMEw921URFfb4f4hQX5j7AAvyYOo/z3g5UB8YX4u5S0ReayVALUUyxiCxx0tviSvfGBsK+Jr5CXv+UsdrgW5qBFaGdEhhWZOWOEC8dSJKOkT+oMhW806+TprQzIUpkLZ0SppE7DUO+rSJO9iGIm95rIfVONqrkgwWc4gzE+eYYyzL132SofTmLVUM08ddZPOdmCA31JVZGOu/ooWdoZtZBBEbBPYRd5CNqD+GiIuHRdx9unHVc0OizZIhGVW77nyr9i+r5c4efDVud/dowi5b+nRX9MlOQ3XLIkorc=
after_success:
- mvn clean test jacoco:report coveralls:report
